In [3]:
from eunjeon import Mecab

mecab = Mecab()
print(mecab.morphs(u'영등포구청역에 있는 맛집 좀 알려주세요.'))

['영등포구청역', '에', '있', '는', '맛집', '좀', '알려', '주', '세요', '.']

In [1]:
#1
#시 row data -> DataFrame으로 변환
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

csv_data = pd.read_csv("C:\DeepLearing\Robot_KSG\poem\poems.csv", names=['제목','시인','본문','etc']) #시 데이터 DataFrame 형태로 불러오기
csv_data = csv_data.drop(['etc'], axis='columns') #etc 열 삭제

csv_data

,제목,시인,본문
0,"1, 2, 3, 4선생-1",서덕출,"1, 2, 3, 4, 선생\n\n서덕출\n\n나는 학교 조그마한\n\n학..."
1,10월의 노래,조명희,10\n\n월의 노래\n\n짓밟힌 무리의 흘린 핏방울 방울이\n\n지심으로 흘러 흘...
2,15일간,박인환,일간15\n\n깨끗한 시트 위에서\n\n나는 몸부림을 쳐도 소용이 없다.\n\n공간...
3,1926년 3월 19일 야심(一九二六年三月十九日夜心)-36,김창술,一九二六年三月十九日夜心\n\n김창술\n\n독와사를 퍼트린드시 숨맥히는이밤의마음에...
4,1929년(一九二九年)-35,김창술,一九二九年\n\n김창술\n\n울엉찬새벽고동이 잠들은이을 흔들어 우네\n\n...
...,...,...,...
4869,落葉-22,김대봉,확실히 落葉소리 인데\n\n落葉소리는 들리지안허\n\n萬衆을 지씹는\n\n暴...
4870,落葉소리-23,김대봉,落葉소리\n\n김대봉\n\n찬서리 나리는 고요한밤에\n\n낙엽이 바싸싹 러...
4871,論介(논개),변영로,論介\n\n논개[\n\n]\n\n거룩한 분노는\n\n종교보다도 깊고\n\n불붙는...
4872,六花六稜(육화육릉),변영로,[\n\n육화육릉\n\n]\n\n[\n\n]\n향락 같이 \n\n短\n\n[\n단명...
4873,履聲滿街(이성만가),변영로,街燈\n\n[\n\n가등 마저 졸음 못 참는 밤거리에\n\n]\n\n街\n\...

In [2]:
#2.1
#불용어 처리1 - 한글,숫자 빼고 제거

csv_data['제목'] = csv_data['제목'].str.replace("[^ㄱ-ㅎㅏ-ㅣ가-힣0-9 ]", "")
csv_data['본문'] = csv_data['본문'].str.replace("[^ㄱ-ㅎㅏ-ㅣ가-힣 ]", "")

In [4]:
#2.2
#mecab으로 data token화
from eunjeon import Mecab

mecab = Mecab()
poems_token = []

for i in range(len(csv_data)): #i: 시 index
    for j in range(3): #j: column index
        poems_token.append(mecab.morphs(csv_data.loc[i][j])) #토큰화 후 poems_token에 1차원 배열로 저장

In [5]:
#2.3
#DataFrame으로 변환
poems_token = np.array(poems_token).reshape(-1,3) #numpy array로 변환
poems_token = pd.DataFrame(poems_token, columns=['제목','시인','본문']) #DataFrame으로 변환

poems_token

,제목,시인,본문
0,"[1, 2, 3, 4, 선생, 1]",[서덕출],"[1, 2, 3, 4, 선생, 서덕출, 나, 는, 학교, 조그마, 한, 학생, 이,..."
1,"[10, 월, 의, 노래]",[조명희],"[10, 월, 의, 노래, 짓밟힌, 무리, 의, 흘린, 핏방울, 방울, 이, 지심,..."
2,"[15, 일, 간]",[박인환],"[일간, 15, 깨끗, 한, 시트, 위, 에서, 나, 는, 몸부림, 을, 쳐도, 소..."
3,"[1926, 년, 3, 월, 19, 일, 야심, 36]","[김창, 술]","[김창, 술독, 와사, 를, 퍼트린, 드, 시, 숨, 맥히, 는, 이, 밤, 의, ..."
4,"[1929, 년, 35]","[김창, 술]","[김창, 술, 울, 엉, 찬, 새벽, 고동, 이, 잠들, 은, 이, 을, 흔들, 어..."
...,...,...,...
4869,[22],[김대봉],"[확실히, 소리, 인데, 소리, 는, 들리, 지, 안, 허, 을, 지, 씹는, 의,..."
4870,"[소리, 23]",[김대봉],"[소리, 김대봉, 찬, 서리, 나리, 는, 고요, 한, 밤, 에, 낙엽, 이, 바,..."
4871,[논개],[변영로],"[논개, 거룩, 한, 분노, 는, 종교, 보다, 도, 깊, 고, 불붙, 는, 정열,..."
4872,"[육, 화육, 릉]",[변영로],"[육, 화육, 릉, 향락, 같이, 단명, 인, 걸, 알, 려거든, 물, 위, 에, ..."
4873,"[이성, 만, 가]",[변영로],"[가등, 마저, 졸음, 못, 참, 는, 밤거리, 에, 이성, 만, 가, 휑, 하, ..."

In [6]:
#2.4
#불용어 처리2 - token 중 불용어 제거

stopwords = np.loadtxt("C:\DeepLearing\Robot_KSG\poem\stopwords.csv", delimiter=',', dtype='str') #stopwords 불러오기

poems_token['제목'] = poems_token['제목'].apply(lambda x: [item for item in x if item not in stopwords])
poems_token['본문'] = poems_token['본문'].apply(lambda x: [item for item in x if item not in stopwords])

poems_token

,제목,시인,본문
0,"[1, 2, 3, 4, 선생, 1]",[서덕출],"[1, 2, 3, 4, 선생, 서덕출, 학교, 조그마, 학생, 집, 와선, 두, 말..."
1,"[10, 월, 노래]",[조명희],"[10, 월, 노래, 짓밟힌, 무리, 흘린, 핏방울, 방울, 지심, 흘러, 흘러, ..."
2,"[15, 일, 간]",[박인환],"[일간, 15, 깨끗, 시트, 위, 몸부림, 쳐도, 소용, 없, 공간, 들려오, 공..."
3,"[1926, 년, 3, 월, 19, 일, 야심, 36]","[김창, 술]","[김창, 술독, 와사, 퍼트린, 드, 시, 숨, 맥히, 밤, 마음, 정, 보, 려는..."
4,"[1929, 년, 35]","[김창, 술]","[김창, 술, 울, 엉, 찬, 새벽, 고동, 잠들, 흔들, 우네, 멀, 케, 눈, ..."
...,...,...,...
4869,[22],[김대봉],"[확실히, 소리, 소리, 들리, 안, 씹는, 수많, 깨, 여짐, 누가, 드라고, 우..."
4870,"[소리, 23]",[김대봉],"[소리, 김대봉, 찬, 서리, 나리, 고요, 밤, 낙엽, 바, 싸, 싹, 면은, 슯..."
4871,[논개],[변영로],"[논개, 거룩, 분노, 종교, 깊, 불붙, 정열, 사랑, 강하, 다아, 강낭콩, 꽃..."
4872,"[육, 화육, 릉]",[변영로],"[육, 화육, 릉, 향락, 단명, 걸, 알, 물, 위, 떨어지, 눈, 보, 양지, ..."
4873,[이성],[변영로],"[가등, 졸음, 못, 밤거리, 이성, 휑, 비인, 거리, 잠들, 고요, 리서, 서로..."

In [7]:
#2.5.1
#csv파일로 내보내기
#poems_token_mecab.csv: 제목, 시인, 본문 토큰화 되어있는 csv 파일

poems_token.to_csv("C:\DeepLearing\Robot_KSG\poem\poems_token_mecab.csv", sep=',', na_rep='NaN')

In [8]:
#2.5.2
#본문 데이터만 정제 및 csv,txt파일로 내보내기
#poems_text_token.csv: 시 본문 토큰화 상태/ poems.txt: 시 본문 데이터

poems_text_token = poems_token['본문'].apply(lambda x: pd.Series(x)) #본문만 다시 dataframe화
poems_text_token.dropna(axis=1, thresh=487, inplace=True) #데이터 10% 이하(NaN 90%이상)인 열 제거 / thresh: 결측치 수치 지정, inplace: 현재 dataframe에 바로 적용

poems_text_token.to_csv("C:\DeepLearing\Robot_KSG\poem\poems_text_token.csv", sep=',', na_rep='NaN')

csv_data['본문'].to_csv('C:\DeepLearing\Robot_KSG\poem\poems.txt', index=False, header=None, sep=' ')

In [9]:
poems_text_token

,0,1,2,3,4,5,6,7,8,9,...,136,137,138,139,140,141,142,143,144,145
0,1,2,3,4,선생,서덕출,학교,조그마,학생,집,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,10,월,노래,짓밟힌,무리,흘린,핏방울,방울,지심,흘러,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,일간,15,깨끗,시트,위,몸부림,쳐도,소용,없,공간,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,김창,술독,와사,퍼트린,드,시,숨,맥히,밤,마음,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,김창,술,울,엉,찬,새벽,고동,잠들,흔들,우네,...,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4869,확실히,소리,소리,들리,안,씹는,수많,깨,여짐,누가,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4870,소리,김대봉,찬,서리,나리,고요,밤,낙엽,바,싸,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4871,논개,거룩,분노,종교,깊,불붙,정열,사랑,강하,다아,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4872,육,화육,릉,향락,단명,걸,알,물,위,떨어지,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4873,가등,졸음,못,밤거리,이성,휑,비인,거리,잠들,고요,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [33]:
#2.5.3
#stopwords.csv -> stopwords.txt 변환(ckonlpy lib 이용을 위한 전처리)

stopwords = pd.read_csv("C:\DeepLearing\Robot_KSG\poem\stopwords.csv")

stopwords.to_csv("C:\DeepLearing\Robot_KSG\poem\stopwords.txt", index=False, header=None, sep='\n')