In [16]:
import pandas as pd
from lda2vec.nlppipe import Preprocessor

In [19]:
#1
#시 token data 불러오기
poems_token = pd.read_csv("C:\DeepLearing\Robot_KSG\poem\poems_text_token.csv", index_col=0) #index_col=0: 맨앞의 열 인덱스로 사용(인덱스 재부여 방지)
poems_token.fillna('-', inplace=True) #NaN -> '-' 로 변환(제거를 위해)

poems_token[:2]

,0,1,2,3,4,5,6,7,8,9,...,136,137,138,139,140,141,142,143,144,145
0,1,2,3,4,선생,서덕출,학교,조그마,학생,집,...,-,-,-,-,-,-,-,-,-,-
1,10,월,노래,짓밟힌,무리,흘린,핏방울,방울,지심,흘러,...,-,-,-,-,-,-,-,-,-,-

In [ ]:
#2
#전처리?
P =